### ISSUE TITLE
`RequestInfo` change to a named tuple broke BC

### ISSUE THREAD

**Issue by bartfeenstra** [fafhrd91/aiohttp#9866]
### Describe the bug

Existing usage of aiohttp 3.10 no longer works with aiohttp 3.13, causing the following error: `TypeError: RequestInfo.__new__() missing 1 required positional argument: 'real_url'`

### To Reproduce

Run the following code:
```
"""
Reproduce a regression in aiohttp 3.11.0.
"""

from multidict import CIMultiDict, CIMultiDictProxy

from aiohttp.client_reqrep import RequestInfo
from yarl import URL

RequestInfo(URL(), "GET", CIMultiDictProxy(CIMultiDict()))
```
With aiohttp 3.10.11, this exits without an error. With aiohttp 3.11.0, this raises `TypeError: RequestInfo.__new__() missing 1 required positional argument: 'real_url'`

### Expected behavior

The expected behavior is for no error to be raised, by `real_url` not being a required argument.

### Logs/tracebacks

```python-traceback
.
```

### Python Version

```console
3.13
```

### aiohttp Version

```console
3.11.0
```

### multidict Version

```console
6.1.0
```

### propcache Version

```console
0.2.0
```

### yarl Version

```console
1.17.1
```

### OS

Ubuntu 24.04

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
This is expected. Its mentioned as breaking in the changelog
<img width="677" alt="Screenshot 2024-11-13 at 1 46 17 PM" src="https://github.com/user-attachments/assets/f45ae766-6f85-4ca5-a110-b8e25076b59b">

**Comment by d1manson** [comment]
fyi this is breaking for https://github.com/pnuckowski/aioresponses

**Comment by bdraco** [comment]
Please see https://github.com/pnuckowski/aioresponses/pull/262

**Comment by bdraco** [comment]
My initial call on this was we didn't want to change it because we don't expect these objects to be created externally but since there is no great alternative to do the mocking, I opened https://github.com/aio-libs/aiohttp/pull/9873
