### ISSUE TITLE
Fails to build on Python 3.11 - longintrepr.h: No such file or directory

### ISSUE THREAD

**Issue by chris-dem** [fafhrd91/aiohttp#6997]
## Describe the bug
 Unable to find longinter when using `env CC=mpicxx pip3.11 install repast4py` on ubuntu WSL

### To Reproduce

I followed the tutorial on https://repast.github.io/repast4py.site/guide/user_guide.html

### Expected behavior

Should have installed normally

### Logs/tracebacks

```python-traceback
In file included from src/MPI.c:4:
            src/mpi4py.MPI.c:198:12: fatal error: longintrepr.h: No such file or directory
              198 |   #include "longintrepr.h"
                  |            ^~~~~~~~~~~~~~~
            compilation terminated.
            error: command '/usr/bin/mpicc' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for mpi4py
      Failed to build mpi4py
      ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### Python Version

```console
$ python --version
3.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Version: 3.8.3
```

### multidict Version

```console
$ python -m pip show multidict
Version: 6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
Version: 1.8.1
```

### OS

Ubuntu 20.04.5 LTS

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Sorry, what does that have to do with aiohttp?

**Comment by chris-dem** [comment]
> Sorry, what does that have to do with aiohttp?

Oh my bad, I have seen this issue occur again on aiohttp and I assumed you guys would know what could be the issue. If not, i will just close the issue

**Comment by Dreamsorcerer** [comment]
If you search for the same issue on aiohttp, you can probably get some hints. But, I think it pretty much just came to updating all our dependencies to get 3.11 support working. You'll need to report an issue with that project to get them to update theirs.
