### ISSUE TITLE
Version 3.10.10 broke all mocks

### ISSUE THREAD

**Issue by adigaboy** [fafhrd91/aiohttp#9512]
### Describe the bug

New version: 3.10.10
Old version: 3.10.5
Python: 3.12.5

I had mocks for test in this manner:
`@patch('aiohttp.client.ClientSession._request')`

For version 3.10.5 in order to mock I was returning an AsyncMock object in this manner:
`def mock_login(*args):
    response = AsyncMock()
    response.release = AsyncMock()
    response.text = AsyncMock()
    response.status=200
    response.json = AsyncMock(return_value={'token': 'test_token'})
    return response
`

After upgrading to 3.10.10 everything is now broken, apperantly the response mechanism changed from using _release_ & _wait_for_close_ to _aenter_ & _aexit_

for example above i had to adjust to:
`def mock_login(*args):
    response = AsyncMock()
    response.release = AsyncMock()
    response.text = AsyncMock()
    response.status=200
    response.json = AsyncMock(return_value={'token': 'test_token'})
    aenter_ojb = AsyncMock()
    aenter_ojb.__aenter__ = AsyncMock(return_value=response)
    return aenter_ojb`

Anyway, in my opinion this stuff should not happen under a patch version or even a minor change.

### To Reproduce

As explained:
Mock with `@patch('aiohttp.client.ClientSession._request')`
With the side_effect:
`def mock_login(*args):
    response = AsyncMock()
    response.release = AsyncMock()
    response.text = AsyncMock()
    response.status=200
    response.json = AsyncMock(return_value={'token': 'test_token'})
    return response
`

### Expected behavior

No need to change the mechanism

### Logs/tracebacks

```python-traceback
AttributeError: 'mock_get_ips' object has no attribute '__aenter__'. Did you mean: '__delattr__'?
```

### Python Version

```console
3.12.0
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.10.10
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /home/.../venv/lib/python3.12/site-packages
Requires: aiohappyeyeballs, aiosignal, attrs, frozenlist, multidict, yarl
Required-by: ***, *** (internal packages)
```

### multidict Version

```console
Name: multidict
Version: 6.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
```

### propcache Version

```console
Name: propcache
Version: 0.2.0
Summary: Accelerated property cache
Home-page: https://github.com/aio-libs/propcache
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
```

### yarl Version

```console
Name: yarl
Version: 1.15.5
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
```

### OS

Linux (Window WSL2)

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Looks like you're mocking a private attribute, those are not public API and can change at any point.

But if this was a public API, it's still a good idea to be in control of your environment: https://hynek.me/articles/semver-will-not-save-you/#taking-responsibility

**Comment by Dreamsorcerer** [comment]
Agreed, it appears you've mocked a private method and then returned a mock object that is incompatible with the return type of ClientResponse. A ClientResponse has a `__aenter__` method, so there is no reason for us to expect that changing the methods we call would break your code.

This seems like an incredibly brittle way to do mocking. I'd suggest maybe looking at aioresponses, which looks a lot easier to use. If you continue using mocking like this, then I'd atleast update it to:
```
resp = mock.create_autospec(ClientResponse, spec_set=True, instance=True)
resp.__aenter__.return_value = resp
```

Which should atleast be somewhat more robust.
