### ISSUE TITLE
Interacting with aiohttp.request results in error (version 3.11.0)

### ISSUE THREAD

**Issue by brent-cybrid** [fafhrd91/aiohttp#9878]
### Describe the bug

We're using the aiohttp.request coroutine, however since updating to v3.11.0 we see the following error:

```python
TypeError: RequestInfo.__new__() missing 1 required positional argument: 'real_url'
```

### To Reproduce

1. Make a call using aiohttp.request, e.g.,

```python
aiohttp.request(method, url, data=body, headers=headers, auth=None, **kwargs) 
```

### Expected behavior

No error would be raised

### Logs/tracebacks

```python-traceback
TypeError: RequestInfo.__new__() missing 1 required positional argument: 'real_url'
```
```


### Python Version

```console
$ python --version

Python 3.12.7
```

### aiohttp Version

```console
$ python -m pip show aiohttp

3.11.0
```

### multidict Version

```console
$ python -m pip show multidict

6.1.0
```

### propcache Version

```console
$ python -m pip show propcache

0.2.0
```

### yarl Version

```console
$ python -m pip show yarl

1.17.1
```

### OS

Mac OS X, Alpine container

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
duplicate of #9866

**Comment by webknjaz** [comment]
@bdraco is this fixed with https://github.com/aio-libs/aiohttp/pull/9875?

**Comment by bdraco** [comment]
> @bdraco is this fixed with #9875?

yes

**Comment by Dreamsorcerer** [comment]
Well, `aiohttp.request()` should work. I'm hoping they just failed to mention they were using aioresponses (which would be obvious if the traceback, as requested in the template, was actually provided...).
