### ISSUE TITLE
Python 3.11 - error: _PyErr_StackItem {aka struct _err_stackitem} has no member named exc_type/exc_traceback

### ISSUE THREAD

**Issue by hrnciar** [fafhrd91/aiohttp#6730]
### Describe the bug

aiohttp doesn't build with Python 3.11

### To Reproduce

Build aiohttp with Python 3.11

### Expected behavior

Builds with Python 3.11

### Logs/tracebacks

```python-traceback
aiohttp/_http_writer.c: In function â€˜__Pyx_ReraiseExceptionâ€™:
aiohttp/_http_writer.c:4736:20: error: â€˜_PyErr_StackItemâ€™ {aka â€˜struct _err_stackitemâ€™} has no member named â€˜exc_typeâ€™
 4736 |     type = exc_info->exc_type;
      |                    ^~
aiohttp/_http_writer.c:4738:18: error: â€˜_PyErr_StackItemâ€™ {aka â€˜struct _err_stackitemâ€™} has no member named â€˜exc_tracebackâ€™
 4738 |     tb = exc_info->exc_traceback;
      |                  ^~
error: command '/usr/bin/gcc' failed with exit code 1

Full log: https://download.copr.fedorainfracloud.org/results/@python/python3.11/fedora-rawhide-x86_64/04354617-python-aiohttp/builder-live.log.gz
```

### Python Version

```console
Python 3.11.0a7
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
6.0.2
```

### yarl Version

```console
1.8.0
```

### OS

Fedora rawhide

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by ghost** [comment]
Fix when

**Comment by Dreamsorcerer** [comment]
Well, 3.8.3 has been released and is built under 3.11, so it must be buildable now...

If you're still getting this error, then you must be building it incorrectly. But, there is no information in the issue how it was built.
