### PR TITLE
allow tests to run without `trustme`

### PR DESCRIPTION
**Pull request by kumaraditya303**
## What do these changes do?
`trustme` is an optional test only dependency, however it is used for annotations which requires it to be installed. This PR fixes the annotations so that tests can be run without trustme.  

## Are there changes in behavior for the user?
No change.

## Is it a substantial burden for the maintainers to support this?
No

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES/` folder
  * name it `<issue_or_pr_num>.<type>.rst` (e.g. `588.bugfix.rst`)
  * if you don't have an issue number, change it to the pull request
    number after creating the PR
    * `.bugfix`: A bug fix for something the maintainers deemed an
      improper undesired behavior that got corrected to match
      pre-agreed expectations.
    * `.feature`: A new behavior, public APIs. That sort of stuff.
    * `.deprecation`: A declaration of future API removals and breaking
      changes in behavior.
    * `.breaking`: When something public is removed in a breaking way.
      Could be deprecated in an earlier release.
    * `.doc`: Notable updates to the documentation structure or build
      process.
    * `.packaging`: Notes for downstreams about unobvious side effects
      and tooling. Changes in the test invocation considerations and
      runtime assumptions.
    * `.contrib`: Stuff that affects the contributor experience. e.g.
      Running tests, building the docs, setting up the development
      environment.
    * `.misc`: Changes that are hard to assign to any of the above
      categories.
  * Make sure to use full sentences with correct case and punctuation,
    for example:
    ```rst
    Fixed issue with non-ascii contents in doctest text files
    -- by :user:`contributor-gh-handle`.
    ```

    Use the past tense or the present tense a non-imperative mood,
    referring to what's changed compared to the last released version
    of this project.

### CODE REVIEW

**Comment by webknjaz** [comment]
Can we figure out how to make it non-optional instead? It's not supposed to be optional in general.

**Comment by kumaraditya303** [comment]
> Can we figure out how to make it non-optional instead? It's not supposed to be optional in general.

`trustme` is a test only dependency and has no support for i686 too [^1], why do you want to make it required? 

[^1]: https://github.com/aio-libs/aiohttp/blob/33de07852848eb51e82ad4132bb7038b27c348ad/requirements/test.in#L17

**Comment by kumaraditya303** [comment]
Keeping `trustme` as optional would allow adding free-threading support and running tests without depending on `cryptography`  which currently doesn't supports free-threading and is blocked on cffi 2.0 release https://github.com/pyca/cryptography/pull/12555/.

**Comment by webknjaz** [comment]
Ah, I see. Let me ask nitz if he has time to release cffi it properly, then...

**Comment by kumaraditya303** [comment]
> Ah, I see. Let me ask nitz if he has time to release cffi it properly, then...

Alright, it still seems like a good idea to me to reduce dependency on trustme/cryptography since most of tests already support running without `trustme`, the issue is mostly about type annotations.

**Comment by webknjaz** [comment]
A lot of tests making HTTP requests would use `trustme`. They'll just be ~skipped~ xfailed if it's not there. It's mandatory for TLS setup when testing.

**Comment by kumaraditya303** [comment]
> A lot of tests making HTTP requests would use trustme. They'll just be skipped xfailed if it's not there. It's mandatory for TLS setup when testing.

Yes it is only needed for tls testing, I had created this PR based on assumption that tls tests are optional [^1] and to be skipped when trustme is not available. Anyways, if you prefer to keep it required then I'll close it and wait for cffi release.

[^1]: https://github.com/aio-libs/aiohttp/blob/33de07852848eb51e82ad4132bb7038b27c348ad/tests/conftest.py#L30

**Comment by webknjaz** [comment]
I think that conditional is only there because it was crashing in some old macos env in the past. But it's doesn't compromise test coverage since there's a lot of other similar envs where it works.
Perhaps, we could get rid of the try/except idiom already. But I haven't tested.
With FT, though, it's a bit different — we would have missing coverage in that env, which may be problematic.

Have you tried testing against the CFFI pre-release? I think, we might be able to use that in the test matrix.

**Comment by Dreamsorcerer** [comment]
If it's causing any downstream issues, I'm open to these changes.

**Comment by kumaraditya303** [comment]
> Have you tried testing against the CFFI pre-release? I think, we might be able to use that in the test matrix.

Using `cffi==2.0.0b1` is not enough because cryptography uses limited C API so it won't compile on 3.14t. 

```
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/Python.h:51:4: error: "The limited API is not currently supported in the free-threaded build"
        cargo:warning=   51 | #  error "The limited API is not currently supported in the free-threaded build"
        cargo:warning=      |    ^
        cargo:warning=In file included from /private/var/folders/gl/y19dp_px79j44r3kss8lm4h40000gn/T/pip-install-tix4j65k/cryptography_3b795e1d3fed45eeb1b478727b4abf47/target/release/build/cryptography-cffi-82cf509fce7ecacb/out/_openssl.c:58:
        cargo:warning=In file included from /Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/Python.h:81:
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/object.h:158:5: error: unknown type name 'PyMutex'
        cargo:warning=  158 |     PyMutex ob_mutex;           // per-object lock
        cargo:warning=      |     ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/object.h:311:5: error: call to undeclared function '_Py_atomic_store_ssize_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  311 |     _Py_atomic_store_ssize_relaxed(&ob->ob_size, size);
        cargo:warning=      |     ^
        cargo:warning=In file included from /private/var/folders/gl/y19dp_px79j44r3kss8lm4h40000gn/T/pip-install-tix4j65k/cryptography_3b795e1d3fed45eeb1b478727b4abf47/target/release/build/cryptography-cffi-82cf509fce7ecacb/out/_openssl.c:58:
        cargo:warning=In file included from /Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/Python.h:82:
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:109:26: error: call to undeclared function '_Py_atomic_load_uint32_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  109 |         uint32_t local = _Py_atomic_load_uint32_relaxed(&ob->ob_ref_local);
        cargo:warning=      |                          ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:109:26: warning: implicit conversion changes signedness: 'int' to 'uint32_t' (aka 'unsigned int') [-Wsign-conversion]
        cargo:warning=  109 |         uint32_t local = _Py_atomic_load_uint32_relaxed(&ob->ob_ref_local);
        cargo:warning=      |                  ~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:113:29: error: call to undeclared function '_Py_atomic_load_ssize_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  113 |         Py_ssize_t shared = _Py_atomic_load_ssize_relaxed(&ob->ob_ref_shared);
        cargo:warning=      |                             ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:126:13: error: call to undeclared function '_Py_atomic_load_uint32_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  126 |     return (_Py_atomic_load_uint32_relaxed(&op->ob_ref_local) ==
        cargo:warning=      |             ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:126:63: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
        cargo:warning=  126 |     return (_Py_atomic_load_uint32_relaxed(&op->ob_ref_local) ==
        cargo:warning=      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
        cargo:warning=  127 |             _Py_IMMORTAL_REFCNT_LOCAL);
        cargo:warning=      |             ~~~~~~~~~~~~~~~~~~~~~~~~~
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:171:9: error: call to undeclared function '_Py_IsOwnedByCurrentThread'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  171 |     if (_Py_IsOwnedByCurrentThread(ob)) {
        cargo:warning=      |         ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:266:22: error: call to undeclared function '_Py_atomic_load_uint32_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  266 |     uint32_t local = _Py_atomic_load_uint32_relaxed(&op->ob_ref_local);
        cargo:warning=      |                      ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:266:22: warning: implicit conversion changes signedness: 'int' to 'uint32_t' (aka 'unsigned int') [-Wsign-conversion]
        cargo:warning=  266 |     uint32_t local = _Py_atomic_load_uint32_relaxed(&op->ob_ref_local);
        cargo:warning=      |              ~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:273:9: error: call to undeclared function '_Py_IsOwnedByCurrentThread'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  273 |     if (_Py_IsOwnedByCurrentThread(op)) {
        cargo:warning=      |         ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:274:9: error: call to undeclared function '_Py_atomic_store_uint32_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  274 |         _Py_atomic_store_uint32_relaxed(&op->ob_ref_local, new_local);
        cargo:warning=      |         ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:277:9: error: call to undeclared function '_Py_atomic_add_ssize'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  277 |         _Py_atomic_add_ssize(&op->ob_ref_shared, (1 << _Py_REF_SHARED_SHIFT));
        cargo:warning=      |         ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:363:22: error: call to undeclared function '_Py_atomic_load_uint32_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  363 |     uint32_t local = _Py_atomic_load_uint32_relaxed(&op->ob_ref_local);
        cargo:warning=      |                      ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:363:22: warning: implicit conversion changes signedness: 'int' to 'uint32_t' (aka 'unsigned int') [-Wsign-conversion]
        cargo:warning=  363 |     uint32_t local = _Py_atomic_load_uint32_relaxed(&op->ob_ref_local);
        cargo:warning=      |              ~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:369:9: error: call to undeclared function '_Py_IsOwnedByCurrentThread'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  369 |     if (_Py_IsOwnedByCurrentThread(op)) {
        cargo:warning=      |         ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:371:9: error: call to undeclared function '_Py_atomic_store_uint32_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  371 |         _Py_atomic_store_uint32_relaxed(&op->ob_ref_local, local);
        cargo:warning=      |         ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:373:13: error: call to undeclared function '_Py_MergeZeroLocalRefcount'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  373 |             _Py_MergeZeroLocalRefcount(op);
        cargo:warning=      |             ^
        cargo:warning=/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t/refcount.h:377:9: error: call to undeclared function '_Py_DecRefShared'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        cargo:warning=  377 |         _Py_DecRefShared(op);
        cargo:warning=      |         ^
        cargo:warning=4 warnings and 16 errors generated.
      
        --- stderr
      
      
        error occurred in cc-rs: command did not execute successfully (status code exit status: 1): env -u IPHONEOS_DEPLOYMENT_TARGET LC_ALL="C" "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-macosx" "-mmacosx-version-min=11.0" "-I" "/opt/homebrew/opt/openssl@3/include" "-I" "/Users/kumaraditya/work/aiohttp/env/include" "-I" "/Users/kumaraditya/.pyenv/versions/3.14t-dev/include/python3.14t" "-Wall" "-Wextra" "-Wconversion" "-Wno-error=sign-conversion" "-Wno-unused-parameter" "-fmacro-prefix-map=/private/var/folders/gl/y19dp_px79j44r3kss8lm4h40000gn/T/pip-install-tix4j65k/cryptography_3b795e1d3fed45eeb1b478727b4abf47/target/release/build/cryptography-cffi-82cf509fce7ecacb/out=." "-DPy_LIMITED_API=0x030700f0" "-o" "/private/var/folders/gl/y19dp_px79j44r3kss8lm4h40000gn/T/pip-install-tix4j65k/cryptography_3b795e1d3fed45eeb1b478727b4abf47/target/release/build/cryptography-cffi-82cf509fce7ecacb/out/22dee0a747e07984-_openssl.o" "-c" "/private/var/folders/gl/y19dp_px79j44r3kss8lm4h40000gn/T/pip-install-tix4j65k/cryptography_3b795e1d3fed45eeb1b478727b4abf47/target/release/build/cryptography-cffi-82cf509fce7ecacb/out/_openssl.c"
      
      
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO MACOSX_DEPLOYMENT_TARGET="11.0" PYO3_BUILD_EXTENSION_MODULE="1" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.14-64bit" PYO3_PYTHON="/Users/kumaraditya/work/aiohttp/env/bin/python" PYTHON_SYS_EXECUTABLE="/Users/kumaraditya/work/aiohttp/env/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--locked" "--manifest-path" "/private/var/folders/gl/y19dp_px79j44r3kss8lm4h40000gn/T/pip-install-tix4j65k/cryptography_3b795e1d3fed45eeb1b478727b4abf47/src/rust/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/cryptography.hazmat.bindings._rust.abi3.so"`
      Rust not found, installing into a temporary directory
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/kumaraditya/work/aiohttp/env/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> cryptography

```

**Comment by kumaraditya303** [comment]
> If it's causing any downstream issues, I'm open to these changes.

FWIW, if we get this in then we can start testing on free-threading immediately, I am working on adding CI for it at https://github.com/aio-libs/aiohttp/pull/11466

**Comment by webknjaz** [comment]
UPD: nitz said he'll be releasing cffi at the beginning of the next week

As for making `trustme` optional temporarily, this PR isn't going to be enough. You'd have to make installing it conditional somehow and switch loading it to `pytest.importorskip()`. Also, quoting annotations is probably unnecessary.

**Comment by kumaraditya303** [comment]
> As for making trustme optional temporarily, this PR isn't going to be enough. You'd have to make installing it conditional somehow and switch loading it to pytest.importorskip(). Also, quoting annotations is probably unnecessary.

That is already done https://github.com/aio-libs/aiohttp/blob/33de07852848eb51e82ad4132bb7038b27c348ad/tests/conftest.py#L29-L37 The only part missing is annotations for which I wrote this PR, anyways lets wait for cffi now.

**Comment by webknjaz** [comment]
> That is already done
> 
> https://github.com/aio-libs/aiohttp/blob/33de07852848eb51e82ad4132bb7038b27c348ad/tests/conftest.py#L29-L37
> 
> The only part missing is annotations for which I wrote this PR, anyways lets wait for cffi now.

No, this is the runtime bit. I was talking about the install time.

**Comment by kumaraditya303** [comment]
> No, this is the runtime bit. I was talking about the install time.

I am doing it for free-threading in https://github.com/aio-libs/aiohttp/pull/11466
